name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build & deploy API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Build & Push Docker Image
      uses: docker/build-push-action@v1
      with:
        node-version: ${{ matrix.node-version }}
